version: "3"

services:
  mysql:
    image: mysql:8
    platform: linux/amd64
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      TZ: UTC
    volumes:
      - db-store:/var/lib/mysql
      - ./mysql/:/docker-entrypoint-initdb.d
      - ./mysql/mysql.cnf:/etc/mysql/conf.d/my.cnf
  java:
    build:
      context: ./java
      dockerfile: DockerFile
    tty: true
    working_dir: /app
    volumes:
      - ../spring_project:/app
    ports:
      - ${SPRING_PORT}:8080
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_URL: ${DB_URL}
    depends_on:
      - mysql
volumes:
  db-store: